spring.application.name=ocorrencias


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update  

# Essa você pode usar se quer que quando criar uma classe ele crie automaticamente no banco também.

spring.jpa.show-sql=true